In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
from sklearn.ensemble import RandomForestClassifier

In [6]:
data = pd.read_csv("train_processed.csv")

In [7]:
data

,Applicant_Gender,Manager_Joining_Designation,Manager_Current_Designation,Manager_Grade,Manager_Status,Manager_Gender,Manager_Num_Application,Manager_Num_Coded,Manager_Business,Manager_Num_Products,...,Applicant_Qualification_Associate/Fellow of Acturial Society of India,Applicant_Qualification_Associate/Fellow of Institute of Company Secretories of India,Applicant_Qualification_Associate/Fellow of Insurance Institute of India,Applicant_Qualification_Certified Associateship of Indian Institute of Bankers,Applicant_Qualification_Class X,Applicant_Qualification_Class XII,Applicant_Qualification_Graduate,Applicant_Qualification_Masters of Business Administration,Applicant_Qualification_Others,Applicant_Qualification_Professional Qualification in Marketing
0,0,1,2,3.0,0,0,2.0,1.0,335249.0,28.0,...,0,0,0,0,0,0,1,0,0,0
1,0,1,2,3.0,0,0,2.0,1.0,335249.0,28.0,...,0,0,0,0,0,1,0,0,0,0
2,0,1,1,2.0,0,0,0.0,0.0,357184.0,24.0,...,0,0,0,0,0,1,0,0,0,0
3,0,1,3,4.0,0,1,0.0,0.0,318356.0,22.0,...,0,0,0,0,0,1,0,0,0,0
4,0,1,1,2.0,0,0,2.0,1.0,230402.0,17.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9522,0,2,2,3.0,1,0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
9523,0,1,2,3.0,0,0,1.0,0.0,102178.0,5.0,...,0,0,0,0,0,0,1,0,0,0
9524,1,2,2,3.0,0,0,0.0,0.0,316126.0,9.0,...,0,0,0,0,0,0,1,0,0,0
9525,0,3,3,4.0,1,0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
9526,1,1,2,3.0,0,0,1.0,0.0,102178.0,5.0,...,0,0,0,0,0,0,1,0,0,0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9527 entries, 0 to 9526
Data columns (total 34 columns):
 #   Column                                                                                 Non-Null Count  Dtype
---  ------                                                                                 --------------  -----
 0   Applicant_Gender                                                                       9527 non-null   int64
 1   Manager_Joining_Designation                                                            9527 non-null   int64
 2   Manager_Current_Designation                                                            9527 non-null   int64
 3   Manager_Grade                                                                          9527 non-null   float64
 4   Manager_Status                                                                         9527 non-null   int64
 5   Manager_Gender                                                                         9527 non-null   int64
 6   Manager_Num_Application                                                                9527 non-null   float64
 7   Manager_Num_Coded                                                                      9527 non-null   float64
 8   Manager_Business                                                                       9527 non-null   float64
 9   Manager_Num_Products                                                                   9527 non-null   float64
 10  Business_Sourced                                                                       9527 non-null   int64
 11  zipcode_grp_x                                                                          9527 non-null   int64
 12  zipcode_grp_y                                                                          9527 non-null   int64
 13  Manager_Joining_Quarter                                                                9527 non-null   int64
 14  Application_Receipt_Quarter                                                            9527 non-null   int64
 15  Manager_Joining_Year                                                                   9527 non-null   int64
 16  Application_Receipt_Year                                                               9527 non-null   int64
 17  Applicant_Marital_Status_M                                                             9527 non-null   int64
 18  Applicant_Marital_Status_S                                                             9527 non-null   int64
 19  Applicant_Marital_Status_W                                                             9527 non-null   int64
 20  Applicant_Occupation_Others                                                            9527 non-null   int64
 21  Applicant_Occupation_Salaried                                                          9527 non-null   int64
 22  Applicant_Occupation_Self Employed                                                     9527 non-null   int64
 23  Applicant_Occupation_Student                                                           9527 non-null   int64
 24  Applicant_Qualification_Associate/Fellow of Acturial Society of India                  9527 non-null   int64
 25  Applicant_Qualification_Associate/Fellow of Institute of Company Secretories of India  9527 non-null   int64
 26  Applicant_Qualification_Associate/Fellow of Insurance Institute of India               9527 non-null   int64
 27  Applicant_Qualification_Certified Associateship of Indian Institute of Bankers         9527 non-null   int64
 28  Applicant_Qualification_Class X                                                        9527 non-null   int64
 29  Applicant_Qualification_Class XII                                                      9527 non-null   int64
 30  Applicant_Qualification_Graduate                                                       9527 non-null   int64
 31  Applicant_Qualification_Masters of Business Administration                             9527 non-null   int64
 32  Applicant_Qualification_Others                                                         9527 non-null   int64
 33  Applicant_Qualification_Professional Qualification in Marketing                        9527 non-null   int64
dtypes: float64(5), int64(29)
memory usage: 2.5 MB

In [9]:
test = data.iloc[:, 10]
test

0       0
1       1
2       0
3       0
4       0
       ..
9522    0
9523    0
9524    0
9525    0
9526    0
Name: Business_Sourced, Length: 9527, dtype: int64

In [10]:
train = data.drop(columns = "Business_Sourced")
train

,Applicant_Gender,Manager_Joining_Designation,Manager_Current_Designation,Manager_Grade,Manager_Status,Manager_Gender,Manager_Num_Application,Manager_Num_Coded,Manager_Business,Manager_Num_Products,...,Applicant_Qualification_Associate/Fellow of Acturial Society of India,Applicant_Qualification_Associate/Fellow of Institute of Company Secretories of India,Applicant_Qualification_Associate/Fellow of Insurance Institute of India,Applicant_Qualification_Certified Associateship of Indian Institute of Bankers,Applicant_Qualification_Class X,Applicant_Qualification_Class XII,Applicant_Qualification_Graduate,Applicant_Qualification_Masters of Business Administration,Applicant_Qualification_Others,Applicant_Qualification_Professional Qualification in Marketing
0,0,1,2,3.0,0,0,2.0,1.0,335249.0,28.0,...,0,0,0,0,0,0,1,0,0,0
1,0,1,2,3.0,0,0,2.0,1.0,335249.0,28.0,...,0,0,0,0,0,1,0,0,0,0
2,0,1,1,2.0,0,0,0.0,0.0,357184.0,24.0,...,0,0,0,0,0,1,0,0,0,0
3,0,1,3,4.0,0,1,0.0,0.0,318356.0,22.0,...,0,0,0,0,0,1,0,0,0,0
4,0,1,1,2.0,0,0,2.0,1.0,230402.0,17.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9522,0,2,2,3.0,1,0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
9523,0,1,2,3.0,0,0,1.0,0.0,102178.0,5.0,...,0,0,0,0,0,0,1,0,0,0
9524,1,2,2,3.0,0,0,0.0,0.0,316126.0,9.0,...,0,0,0,0,0,0,1,0,0,0
9525,0,3,3,4.0,1,0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
9526,1,1,2,3.0,0,0,1.0,0.0,102178.0,5.0,...,0,0,0,0,0,0,1,0,0,0

In [11]:
train.shape, test.shape

((9527, 33), (9527,))

In [12]:
train_columns = train.columns
train_columns

Index(['Applicant_Gender', 'Manager_Joining_Designation',
       'Manager_Current_Designation', 'Manager_Grade', 'Manager_Status',
       'Manager_Gender', 'Manager_Num_Application', 'Manager_Num_Coded',
       'Manager_Business', 'Manager_Num_Products', 'zipcode_grp_x',
       'zipcode_grp_y', 'Manager_Joining_Quarter',
       'Application_Receipt_Quarter', 'Manager_Joining_Year',
       'Application_Receipt_Year', 'Applicant_Marital_Status_M',
       'Applicant_Marital_Status_S', 'Applicant_Marital_Status_W',
       'Applicant_Occupation_Others', 'Applicant_Occupation_Salaried',
       'Applicant_Occupation_Self Employed', 'Applicant_Occupation_Student',
       'Applicant_Qualification_Associate/Fellow of Acturial Society of India',
       'Applicant_Qualification_Associate/Fellow of Institute of Company Secretories of India',
       'Applicant_Qualification_Associate/Fellow of Insurance Institute of India',
       'Applicant_Qualification_Certified Associateship of Indian Institute of Bankers',
       'Applicant_Qualification_Class X', 'Applicant_Qualification_Class XII',
       'Applicant_Qualification_Graduate',
       'Applicant_Qualification_Masters of Business Administration',
       'Applicant_Qualification_Others',
       'Applicant_Qualification_Professional Qualification in Marketing'],
      dtype='object')

In [13]:
scaler = StandardScaler()

train = scaler.fit_transform(train)

train = pd.DataFrame(data = train, columns = train_columns)

train

,Applicant_Gender,Manager_Joining_Designation,Manager_Current_Designation,Manager_Grade,Manager_Status,Manager_Gender,Manager_Num_Application,Manager_Num_Coded,Manager_Business,Manager_Num_Products,...,Applicant_Qualification_Associate/Fellow of Acturial Society of India,Applicant_Qualification_Associate/Fellow of Institute of Company Secretories of India,Applicant_Qualification_Associate/Fellow of Insurance Institute of India,Applicant_Qualification_Certified Associateship of Indian Institute of Bankers,Applicant_Qualification_Class X,Applicant_Qualification_Class XII,Applicant_Qualification_Graduate,Applicant_Qualification_Masters of Business Administration,Applicant_Qualification_Others,Applicant_Qualification_Professional Qualification in Marketing
0,-0.561065,-0.737807,-0.203566,-0.223319,-0.773621,-0.382688,0.061187,0.254327,0.590431,2.577030,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,-1.273149,1.407449,-0.088477,-0.118533,-0.010246
1,-0.561065,-0.737807,-0.203566,-0.223319,-0.773621,-0.382688,0.061187,0.254327,0.590431,2.577030,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,0.785454,-0.710505,-0.088477,-0.118533,-0.010246
2,-0.561065,-0.737807,-1.226979,-1.134088,-0.773621,-0.382688,-0.897574,-0.606410,0.673043,2.086214,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,0.785454,-0.710505,-0.088477,-0.118533,-0.010246
3,-0.561065,-0.737807,0.819848,0.687451,-0.773621,2.613095,-0.897574,-0.606410,0.526808,1.840806,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,0.785454,-0.710505,-0.088477,-0.118533,-0.010246
4,-0.561065,-0.737807,-1.226979,-1.134088,-0.773621,-0.382688,0.061187,0.254327,0.195555,1.227285,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,0.785454,-0.710505,-0.088477,-0.118533,-0.010246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9522,-0.561065,0.489552,-0.203566,-0.223319,1.292622,-0.382688,-0.897574,-0.606410,-0.672187,-0.858684,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,-1.273149,1.407449,-0.088477,-0.118533,-0.010246
9523,-0.561065,-0.737807,-0.203566,-0.223319,-0.773621,-0.382688,-0.418194,-0.606410,-0.287364,-0.245163,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,-1.273149,1.407449,-0.088477,-0.118533,-0.010246
9524,1.782323,0.489552,-0.203566,-0.223319,-0.773621,-0.382688,-0.897574,-0.606410,0.518410,0.245653,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,-1.273149,1.407449,-0.088477,-0.118533,-0.010246
9525,-0.561065,1.716911,0.819848,0.687451,1.292622,-0.382688,-0.897574,-0.606410,-0.672187,-0.858684,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,0.785454,-0.710505,-0.088477,-0.118533,-0.010246
9526,1.782323,-0.737807,-0.203566,-0.223319,-0.773621,-0.382688,-0.418194,-0.606410,-0.287364,-0.245163,...,-0.010246,-0.010246,-0.010246,-0.010246,-0.155526,-1.273149,1.407449,-0.088477,-0.118533,-0.010246

In [14]:
x_train, x_test, y_train, y_test = train_test_split(train, test, test_size = 0.3, stratify = test, random_state = 42)

In [15]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((6668, 33), (6668,), (2859, 33), (2859,))

In [16]:
classifier = LogisticRegression(class_weight = "balanced")

In [17]:
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
print('Accuracy on training set:',classifier.score(x_train,y_train))
print('Accuracy on test set:',classifier.score(x_test,y_test))

Accuracy on training set: 0.7675464907018597
Accuracy on test set: 0.7604057362714236

In [19]:
rf_clf = RandomForestClassifier(random_state = 42, n_estimators = 100)

In [20]:
rf_clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [21]:
print('Accuracy on training set:',rf_clf.score(x_train,y_train))
print('Accuracy on test set:',rf_clf.score(x_test,y_test))

Accuracy on training set: 0.9548590281943611
Accuracy on test set: 0.7408184679958028